# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Private_Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(default='NULL', max_length=500)),
                ('access_key', models.TextField(default='NULL', max_length=500)),
            ],
        ),
    ]
